### ISSUE TITLE
FP8 still works in pytorch 2.9.1? I get an error: llvm.fmul' op operand #0 must be floating point LLVM type or LLVM dialect-compatible vector of floating point LLVM type, but got 'i8'

### ISSUE THREAD

**Issue by Ph0rk0z** [woct0rdho/triton-windows#176]
On torch 2.7 ampere FP8 patch works flawlessly but as soon as I upgrade to 2.9.1 This error occurs. I have debugged it as far as I am able to and run around the triton code. The NV FP8 types are no longer being cast and just passed directly to mlir which turns them into int8 and bob's your uncle.

<details>
<summary>Incorrect types passed to mlir:</summary>

```
/tmp/torchinductor_supermicro/j5/cj5kapwfinynamoqhvvvkblee6mdzxowfpasjvmmdp26tzyhz2g7.py:28:18: error: 'llvm.fmul' op operand #0 must be floating point LLVM type or LLVM dialect-compatible vector of floating point LLVM type, but got 'i8'
    tmp4 = tmp0 * tmp3
                 ^
#blocked = #ttg.blocked<{sizePerThread = [8], threadsPerWarp = [32], warpsPerCTA = [4], order = [0]}>
module attributes {"ttg.num-ctas" = 1 : i32, "ttg.num-warps" = 4 : i32, ttg.target = "cuda:75", "ttg.threads-per-warp" = 32 : i32} {
  tt.func public @triton_poi_fused_mul_1(%arg0: !tt.ptr<f8E4M3FN> {tt.divisibility = 16 : i32}, %arg1: !tt.ptr<f32> {tt.divisibility = 16 : i32}, %arg2: !tt.ptr<f8E4M3FN> {tt.divisibility = 16 : i32}, %arg3: i32 {tt.divisibility = 16 : i32}) attributes {noinline = false} {
    %c1024_i32 = arith.constant 1024 : i32
    %0 = tt.get_program_id x : i32
    %1 = arith.muli %0, %c1024_i32 : i32
    %2 = tt.make_range {end = 1024 : i32, start = 0 : i32} : tensor<1024xi32, #blocked>
    %3 = tt.splat %1 : i32 -> tensor<1024xi32, #blocked>
    %4 = arith.addi %3, %2 : tensor<1024xi32, #blocked>
    %5 = tt.splat %arg0 : !tt.ptr<f8E4M3FN> -> tensor<1024x!tt.ptr<f8E4M3FN>, #blocked>
    %6 = tt.addptr %5, %4 : tensor<1024x!tt.ptr<f8E4M3FN>, #blocked>, tensor<1024xi32, #blocked>
    %7 = tt.load %6 : tensor<1024x!tt.ptr<f8E4M3FN>, #blocked>
    %8 = tt.load %arg1 : !tt.ptr<f32>
    %9 = tt.fp_to_fp %8, rounding = rtne : f32 -> f8E4M3FN
    %10 = tt.splat %9 : f8E4M3FN -> tensor<1024xf8E4M3FN, #blocked>
    %11 = arith.mulf %7, %10 : tensor<1024xf8E4M3FN, #blocked>
    %12 = tt.splat %arg2 : !tt.ptr<f8E4M3FN> -> tensor<1024x!tt.ptr<f8E4M3FN>, #blocked>
    %13 = tt.addptr %12, %4 : tensor<1024x!tt.ptr<f8E4M3FN>, #blocked>, tensor<1024xi32, #blocked>
    tt.store %13, %11 : tensor<1024x!tt.ptr<f8E4M3FN>, #blocked>
    tt.return
  }
}

```
</details>
<details>
<summary>And when it is correct, things are being cast:</summary>

```
module attributes {"ttg.num-ctas" = 1 : i32, "ttg.num-warps" = 4 : i32, ttg.target = "cuda:75", "ttg.threads-per-warp" = 32 : i32} {
  tt.func public @triton_poi_fused_mul_2(%arg0: !tt.ptr<f16> {tt.divisibility = 16 : i32} loc("/tmp/torchinductor_supermicro/hu/chufutjjnn5ysadmfs2miftexgx2jkpu5b5uesovz3ajhw7zsbya.py":18:0), %arg1: !tt.ptr<f16> {tt.divisibility = 16 : i32} loc("/tmp/torchinductor_supermicro/hu/chufutjjnn5ysadmfs2miftexgx2jkpu5b5uesovz3ajhw7zsbya.py":18:0), %arg2: !tt.ptr<f64> {tt.divisibility = 16 : i32} loc("/tmp/torchinductor_supermicro/hu/chufutjjnn5ysadmfs2miftexgx2jkpu5b5uesovz3ajhw7zsbya.py":18:0), %arg3: i32 {tt.divisibility = 16 : i32} loc("/tmp/torchinductor_supermicro/hu/chufutjjnn5ysadmfs2miftexgx2jkpu5b5uesovz3ajhw7zsbya.py":18:0)) attributes {noinline = false} {
    %cst = arith.constant dense<1.000000e+00> : tensor<128xf64, #blocked> loc(#loc1)
    %cst_0 = arith.constant dense<0.000000e+00> : tensor<128xf16, #blocked> loc(#loc1)
    %cst_1 = arith.constant dense<1.000000e+04> : tensor<128xf64, #blocked> loc(#loc1)
    %cst_2 = arith.constant dense<8.750000e-01> : tensor<128xf64, #blocked> loc(#loc1)
    %cst_3 = arith.constant dense<7> : tensor<128xi32, #blocked> loc(#loc1)
    %cst_4 = arith.constant dense<0.000000e+00> : tensor<128xf64, #blocked> loc(#loc1)
    %cst_5 = arith.constant dense<1.250000e-01> : tensor<128xf64, #blocked> loc(#loc1)
    %cst_6 = arith.constant dense<4.000000e+00> : tensor<128xf32, #blocked> loc(#loc1)
    %cst_7 = arith.constant dense<-112> : tensor<128xi32, #blocked> loc(#loc1)
    %cst_8 = arith.constant dense<3> : tensor<128xi32, #blocked> loc(#loc1)
    %cst_9 = arith.constant dense<112> : tensor<128xi64, #blocked> loc(#loc1)
    %cst_10 = arith.constant dense<8> : tensor<128xi32, #blocked> loc(#loc1)
    %cst_11 = arith.constant dense<29696> : tensor<128xi32, #blocked> loc(#loc1)
    %c128_i32 = arith.constant 128 : i32 loc(#loc1)
    %0 = tt.get_program_id x : i32 loc(#loc2)
    %1 = arith.muli %0, %c128_i32 : i32 loc(#loc3)
    %2 = tt.make_range {end = 128 : i32, start = 0 : i32} : tensor<128xi32, #blocked> loc(#loc4)
    %3 = tt.splat %1 : i32 -> tensor<128xi32, #blocked> loc(#loc5)
    %4 = arith.addi %3, %2 : tensor<128xi32, #blocked> loc(#loc5)
    %5 = arith.cmpi slt, %4, %cst_11 : tensor<128xi32, #blocked> loc(#loc6)
    %6 = arith.divsi %4, %cst_10 : tensor<128xi32, #blocked> loc(#loc7)
    %7 = arith.remsi %4, %cst_10 : tensor<128xi32, #blocked> loc(#loc8)
    %8 = arith.extsi %6 : tensor<128xi32, #blocked> to tensor<128xi64, #blocked> loc(#loc9)
    %9 = arith.cmpi slt, %8, %cst_9 : tensor<128xi64, #blocked> loc(#loc9)
    %10 = arith.muli %6, %cst_8 : tensor<128xi32, #blocked> loc(#loc10)
    %11 = tt.splat %arg0 : !tt.ptr<f16> -> tensor<128x!tt.ptr<f16>, #blocked> loc(#loc11)
    %12 = tt.addptr %11, %10 : tensor<128x!tt.ptr<f16>, #blocked>, tensor<128xi32, #blocked> loc(#loc11)
    %13 = arith.andi %5, %9 : tensor<128xi1, #blocked> loc(#loc12)
    %14 = tt.load %12, %13, %cst_0 evictionPolicy = evict_last : tensor<128x!tt.ptr<f16>, #blocked> loc(#loc13)
    %15 = arith.extf %14 : tensor<128xf16, #blocked> to tensor<128xf32, #blocked> loc(#loc14)
    %16 = arith.cmpi sge, %8, %cst_9 : tensor<128xi64, #blocked> loc(#loc15)
    %17 = arith.addi %6, %cst_7 : tensor<128xi32, #blocked> loc(#loc16)
    %18 = arith.muli %17, %cst_8 : tensor<128xi32, #blocked> loc(#loc17)
    %19 = tt.splat %arg1 : !tt.ptr<f16> -> tensor<128x!tt.ptr<f16>, #blocked> loc(#loc18)
    %20 = tt.addptr %19, %18 : tensor<128x!tt.ptr<f16>, #blocked>, tensor<128xi32, #blocked> loc(#loc18)
    %21 = arith.andi %5, %16 : tensor<128xi1, #blocked> loc(#loc19)
    %22 = tt.load %20, %21, %cst_0 evictionPolicy = evict_last : tensor<128x!tt.ptr<f16>, #blocked> loc(#loc20)
    %23 = arith.extf %22 : tensor<128xf16, #blocked> to tensor<128xf32, #blocked> loc(#loc21)
    %24 = arith.select %9, %15, %23 : tensor<128xi1, #blocked>, tensor<128xf32, #blocked> loc(#loc22)
    %25 = arith.extf %24 : tensor<128xf32, #blocked> to tensor<128xf64, #blocked> loc(#loc23)
    %26 = arith.sitofp %7 : tensor<128xi32, #blocked> to tensor<128xf32, #blocked> loc(#loc24)
    %27 = arith.cmpf olt, %26, %cst_6 : tensor<128xf32, #blocked> loc(#loc25)
    %28 = arith.sitofp %7 : tensor<128xi32, #blocked> to tensor<128xf64, #blocked> loc(#loc26)
    %29 = arith.mulf %28, %cst_5 : tensor<128xf64, #blocked> loc(#loc27)
    %30 = arith.addf %29, %cst_4 : tensor<128xf64, #blocked> loc(#loc28)
    %31 = arith.subi %cst_3, %7 : tensor<128xi32, #blocked> loc(#loc29)
    %32 = arith.sitofp %31 : tensor<128xi32, #blocked> to tensor<128xf64, #blocked> loc(#loc30)
    %33 = arith.mulf %32, %cst_5 : tensor<128xf64, #blocked> loc(#loc31)
    %34 = arith.subf %cst_2, %33 : tensor<128xf64, #blocked> loc(#loc32)
    %35 = arith.select %27, %30, %34 : tensor<128xi1, #blocked>, tensor<128xf64, #blocked> loc(#loc33)
    %36 = tt.extern_elementwise %cst_1, %35 {libname = "", libpath = "", pure = true, symbol = "__nv_pow"} : (tensor<128xf64, #blocked>, tensor<128xf64, #blocked>) -> tensor<128xf64, #blocked> loc(#loc34)
    %37 = arith.divf %cst, %36 : tensor<128xf64, #blocked> loc(#loc35)
    %38 = arith.mulf %25, %37 : tensor<128xf64, #blocked> loc(#loc36)
    %39 = tt.splat %arg2 : !tt.ptr<f64> -> tensor<128x!tt.ptr<f64>, #blocked> loc(#loc37)
    %40 = tt.addptr %39, %4 : tensor<128x!tt.ptr<f64>, #blocked>, tensor<128xi32, #blocked> loc(#loc37)
    tt.store %40, %38, %5 : tensor<128x!tt.ptr<f64>, #blocked> loc(#loc38)
    tt.return loc(#loc39)
  } loc(#loc)
} loc(#loc)
```
</details>

Is this working for you on windows still? On linux I have built triton and it's llvm from source but now tearing my hair out. Is the bug in pytorch itself and how it handles FP8? Did I do something else wrong? Same behavior on SM80 and SM75 and same errors.

**Comment by woct0rdho** [comment]
Could you show the workflow?

**Comment by drozbay** [comment]
Same issue here on an RTX 5090 (SM120) running ComfyUI with fp8 scaled models.
Running PyTorch 2.9.1+cu130, triton-windows 3.5.1.post23, CUDA 13.0, Python 3.13 embedded, Windows 11.
I'm hitting this with FP8 scaled diffusion models ,exact same 'llvm.fmul' op operand #0 must be floating point LLVM type... but got 'i8' error on the scale conversion kernel.
FP16 models + torch.compile works fine. FP8 models without torch.compile also work fine. It's specifically the FP8 + compile combination that breaks.
Also getting the unet unexpected: [scaled_fp8], but I think that's just a logging quirk, ComfyUI should handle that properly. I am unsure if this is a problem with how ComfyUI is passing the weights to the the triton compilation system.

**Comment by woct0rdho** [comment]
A few months ago ComfyUI started to advocate the use of `MixedPrecisionOps`, which actually does fp8 matmul, rather than casting fp8 to fp16 then doing matmul, see https://github.com/comfyanonymous/ComfyUI/pull/10715 . But I haven't checked how well it supports `torch.compile`. On GPUs with sm < 89 we surely need to let it fallback to casting fp8 to fp16. I'll check it when I'm a bit less busy.

**Comment by Ph0rk0z** [comment]
So what's weird is that it works on torch 2.7, even with mixed precision weights. I don't change comfy in between. Hope a node gets made for those kernels, would probably solve a few things.

**Comment by woct0rdho** [comment]
Things are still changing in PyTorch 2.10, and currently comfy-kitchen is not fully working with full graph compilation. I'll try it again when I have time.
