### ISSUE TITLE
AttributeError: type object 'CompiledKernel' has no attribute 'launch_enter_hook'

### ISSUE THREAD

**Issue by CeroxeAnivie** [woct0rdho/triton-windows#137]
### Describe the bug

Firstly, I ran update_comfyui.bat and then entered
"D:\ComfyUI_windows_portable\python_embeded"， And open cmd to enter this folder
Then I used two commands to install, they were

`python -m pip install  https://github.com/woct0rdho/SageAttention/releases/download/v2.2.0-windows/sageattention-2.2.0 +cu128torch2.7.1-cp312-cp312-win_amd64.whl`

`python -m pip install -U "triton-windows<3.5"`

Finally, I downloaded python_3.12.7_clube_libs.zip and placed two of the folders in the python_ embedded folder，then open ComfyUI

My workflow 

[Wan_FusionX_i2v_wrapper_WF.json](https://github.com/user-attachments/files/21539492/Wan_FusionX_i2v_wrapper_WF.json)

Is there a problem with my installation method ？

FETCH ComfyRegistry Data: 40/93
FETCH ComfyRegistry Data: 45/93
Requested to load CLIPVisionModelProjection
loaded completely 12155.5744140625 1208.09814453125 True
FETCH ComfyRegistry Data: 50/93
Clip embeds shape: torch.Size([1, 257, 1280]), dtype: torch.float32
Combined clip embeds shape: torch.Size([1, 257, 1280])
FETCH ComfyRegistry Data: 55/93
Detected model in_channels: 36
Model type: i2v, num_heads: 40, num_layers: 40
Model variant detected: 14B
model_type FLOW
Using accelerate to load and assign model weights to device...
Loading transformer parameters to cpu:  87%|████████████████████████████████▏    | 1133/1303 [00:01<00:00, 1425.13it/s]FETCH ComfyRegistry Data: 60/93
Loading transformer parameters to cpu: 100%|█████████████████████████████████████| 1303/1303 [00:01<00:00, 1118.33it/s]
D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-WanVideoWrapper\nodes.py:1197: FutureWarning: Accessing config attribute `vace_layers` directly via 'WanModel' object attribute is deprecated. Please access 'vace_layers' over 'WanModel's config object instead, e.g. 'unet.config.vace_layers'.
  if transformer.vace_layers is not None:
timesteps: tensor([999, 944, 831, 687, 534, 390, 277, 222], device='cuda:0')
image_cond shape: torch.Size([20, 21, 96, 64])
D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-WanVideoWrapper\nodes.py:1640: FutureWarning: Accessing config attribute `vace_layers` directly via 'WanModel' object attribute is deprecated. Please access 'vace_layers' over 'WanModel's config object instead, e.g. 'unet.config.vace_layers'.
  if transformer.vace_layers is not None:
Swapping 20 transformer blocks
Initializing block swap:  70%|███████████████████████████████████████▉                 | 28/40 [00:04<00:03,  3.96it/s]FETCH ComfyRegistry Data: 65/93
Initializing block swap:  88%|█████████████████████████████████████████████████▉       | 35/40 [00:09<00:02,  1.83it/s]FETCH ComfyRegistry Data: 70/93
Initializing block swap: 100%|█████████████████████████████████████████████████████████| 40/40 [00:13<00:00,  3.06it/s]
D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-WanVideoWrapper\wanvideo\modules\model.py:1261: FutureWarning: Accessing config attribute `vace_layers` directly via 'WanModel' object attribute is deprecated. Please access 'vace_layers' over 'WanModel's config object instead, e.g. 'unet.config.vace_layers'.
  if vace_blocks_to_swap > 0 and self.vace_layers is not None:
----------------------
Block swap memory summary:
Transformer blocks on cpu: 7705.21MB
Transformer blocks on cuda:0: 7705.21MB
Total memory used by transformer blocks: 15410.43MB
Non-blocking memory transfer: True
----------------------
Seq len: 32256
Sampling 81 frames at 512x768 with 8 steps
  0%|                                                                                            | 0/8 [00:00<?, ?it/s]W0801 08:03:34.767000 17136 Lib\site-packages\torch\_inductor\utils.py:1250] [1/0_1] Not enough SMs to use max_autotune_gemm mode
  0%|                                                                                            | 0/8 [00:04<?, ?it/s]
FETCH ComfyRegistry Data: 75/93
!!! Exception during processing !!! AttributeError: type object 'CompiledKernel' has no attribute 'launch_enter_hook'

Set TORCHDYNAMO_VERBOSE=1 for the internal stack trace (please do this especially if you're reporting a bug to PyTorch). For even more developer context, set TORCH_LOGS="+dynamo"

Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 496, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 315, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 289, in _async_map_node_over_list
    await process_inputs(input_dict, i)
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 277, in process_inputs
    result = f(**inputs)
             ^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-WanVideoWrapper\nodes.py", line 2700, in process
    noise_pred, self.cache_state = predict_with_cfg(
                                   ^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-WanVideoWrapper\nodes.py", line 1981, in predict_with_cfg
    noise_pred_cond, cache_state_cond = transformer(
                                        ^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-WanVideoWrapper\wanvideo\modules\model.py", line 1801, in forward
    x = block(x, **kwargs)
        ^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\_dynamo\eval_frame.py", line 663, in _fn
    raise e.remove_dynamo_frames() from None  # see TORCHDYNAMO_VERBOSE=1
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\_inductor\compile_fx.py", line 760, in _compile_fx_inner
    raise InductorError(e, currentframe()).with_traceback(
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\_inductor\compile_fx.py", line 745, in _compile_fx_inner
    mb_compiled_graph = fx_codegen_and_compile(
                        ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\_inductor\compile_fx.py", line 1295, in fx_codegen_and_compile
    return scheme.codegen_and_compile(gm, example_inputs, inputs_to_check, graph_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\_inductor\compile_fx.py", line 1197, in codegen_and_compile
    compiled_fn = graph.compile_to_module().call
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\_inductor\graph.py", line 2083, in compile_to_module
    return self._compile_to_module()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\_inductor\graph.py", line 2130, in _compile_to_module
    mod = PyCodeCache.load_by_key_path(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\_inductor\codecache.py", line 2747, in load_by_key_path
    mod = _reload_python_module(key, path)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\_inductor\runtime\compile_tasks.py", line 36, in _reload_python_module
    exec(code, mod.__dict__, mod.__dict__)
  File "C:\Users\ADMINI~1\AppData\Local\Temp\torchinductor_Administrator\fv\cfvb22rprcpqjip566buzrl5acsklerqruhu4jb32filcd7hqyll.py", line 61, in <module>
    triton_red_fused__to_copy_add_addcmul_native_layer_norm_0 = async_compile.triton('triton_red_fused__to_copy_add_addcmul_native_layer_norm_0', '''
                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\_inductor\async_compile.py", line 346, in triton
    kernel.precompile(warm_cache_only=False)
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\_inductor\runtime\triton_heuristics.py", line 277, in precompile
    self._make_launchers()
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\_inductor\runtime\triton_heuristics.py", line 434, in _make_launchers
    launchers.append(result.make_launcher())
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\_inductor\runtime\triton_heuristics.py", line 1153, in make_launcher
    "launch_enter_hook": binary.__class__.launch_enter_hook,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch._inductor.exc.InductorError: AttributeError: type object 'CompiledKernel' has no attribute 'launch_enter_hook'

Set TORCHDYNAMO_VERBOSE=1 for the internal stack trace (please do this especially if you're reporting a bug to PyTorch). For even more developer context, set TORCH_LOGS="+dynamo"

### Environment details

RTX5080 16G GPU

<img width="1980" height="1091" alt="Image" src="https://github.com/user-attachments/assets/3fe664ec-b0d4-4118-9926-562794b60773" />

**Comment by woct0rdho** [comment]
Triton 3.4 only works with PyTorch >= 2.8 (for now it's pre-release, not officially released). You're using PyTorch 2.7 . You need to install Triton 3.3:
```pwsh
python -m pip install -U "triton-windows<3.4"
```

**Comment by CeroxeAnivie** [comment]
The problem has been solved, thank you (: D
