### PR TITLE
Enable F8E4M3 conversions on Nvidia GPUs with sm < 89, and fix F8E5M2 conversions

### PR DESCRIPTION
**Pull request by woct0rdho**
## Motivation

Nvidia GPUs with sm < 89 are still widely used, see e.g. Steam hardware survey. When running large AI models, a common usage is to store the parameters in fp8, and cast them to fp16 for computation on hardware that doesn't have native fp8. This reduces the memory requirement, even though no speed advantage. This PR aims to enable `torch.compile` on this usage.

We may refer to XLA's fallback mechanism for fp8 operations, see https://github.com/openxla/xla/discussions/23124 , although I think we only need to support the conversions rather than all arithmetic operations.

## Implementation

Before https://github.com/triton-lang/triton/pull/2105 , there were some PTX code for converting F8E4M3/F8E5M2 <-> F16/BF16, but they did not correctly handle denormalized values and rounding to nearest even (RTNE). I've fixed these cases, and added the code for F32 -> F8E4M3/F8E5M2.

I've tested that for all 2^8 F8E4M3/F8E5M2 values, all 2^16 F16/BF16 values, and all 2^32 F32 values, the conversion results are bitwise identical to the [PyTorch implementation](https://github.com/pytorch/pytorch/blob/5e2ef2a465f79957faf5c56fe2a66d7a9b18e1a2/torch/headeronly/util/Float8_e4m3fn.h), except some glitches about inf and nan, see the comments. The tests in `test_conversions.py` are passed.

I've checked that all unit tests are passed on RTX 3080 (sm86). There is no IR change for sm >= 90. For sm89, there is a minor change that previously F32 -> F8E4M3/F8E5M2 was implemented by F32 -> F16 -> F8E4M3/F8E5M2 without correct RTNE, now it's directly implemented with RTNE.

### CODE REVIEW

**Comment by woct0rdho** [comment]
Let me try to upstream it: https://github.com/triton-lang/triton/pull/7904

**Comment by jtabox** [comment]
Hi, great addition to the library. Just a couple questions:

1. This doesn't require PyTorch nightly right? I have latest stable (`2.8.0`).
2. Are there more "installation steps" than just downloading the build you linked a couple posts ago, unzipping and installing the Python wheel? It's `triton-windows` is `3.4.0+gita4ccd09a.post21.fp8`, `triton` is still at `3.3.0` but I don't think it matters, it's kinda en empty redirector, right?
3. Is it mostly FP8 or GGUF models that are supposed to get most benefit?

I'm asking because I just downloaded it, and as a first impression, I *think* things feel slightly slower than usual. That's *completely subjective* though with only minimal testing (as in, installed it and ran 2-3 inferences).

I'll reinstall the stable Triton release, take some measurements and reinstall this one to compare. It's just that intuitively it didn't really feel like things were suddenly much more fast.

This is where I run Comfy:

```
- RTX 3080 (10 GB version)
- 32 GB RAM
- System CUDA: 12.9
- Python: 3.11
- Torch: 2.8.0+cu129
- Sage attn: 2.2.0+cu128torch2.8.0.post2
```

No Pinokio or standalone Python or such, just git cloned the repo and made a Conda env.

**Comment by woct0rdho** [comment]
@jtabox The wheels above should work for both PyTorch 2.8.0 and the recent nightly versions. If you need older versions of Triton for older versions of PyTorch, I can also build the wheels.

Yes you can just install the wheel. What do you mean by `triton is still at 3.3.0`? If you've installed `triton-windows`, you don't need to install another package named `triton`.

fp8 model should be more accurate than GGUF Q4, but it's hard to say whether it's more accurate than GGUF Q8. Also you can do some tests to see which one is faster.

You need to be careful when taking an objective speed test. Run the same workflow, and only change the Triton version. Exit ComfyUI when reinstalling Triton. After starting ComfyUI, run the workflow once to let everything load, then run it again to see the real speed.

**Comment by FurkanGozukara** [comment]
@woct0rdho do you recommend to move Pytorch 2.8 now? i am still on 2.7 and it works so far on everything

**Comment by woct0rdho** [comment]
@FurkanGozukara You can move to PyTorch 2.8, especially because the performance on Blackwell GPUs will be better.

In some cases `torch.compile` does not work well in PyTorch 2.8, but it also does not work well in PyTorch 2.7, and it will be better in the next version of PyTorch.

**Comment by FurkanGozukara** [comment]
awesome thanks.

**Comment by woct0rdho** [comment]
Let me merge this and see how it rolls out. I hoped this could be superseded by GGUF + better `torch.compile` or Nunchaku, but as of PyTorch 2.9 I realized that fp8 + the block swap in ComfyUI-WanVideoWrapper (or [ComfyUI-wanBlockswap](https://github.com/orssorbit/ComfyUI-wanBlockswap) for native workflows) runs faster and causes less recompilation than GGUF + the block swap in ComfyUI-GGUF.

This is the first feature in the 'core' part (rather than the Windows support code) that's deliberately different from the official Triton. It should also work on Linux but I'm not sure what's the best way to publish Linux wheels.

**Comment by jprsyt5** [comment]
I'm trying the newest release, 3.5.0-post21, and encountered this error.

```
Requested to load WAN21
loaded partially 5616.674973297119 5604.770568847656 642
(RES4LYF) rk_type: res_2s
  0%|                                                                                            | 0/4 [00:00<?, ?it/s]!!! Exception during processing !!! backend='inductor' raised:
ImportError: cannot import name 'triton_key' from 'triton.compiler.compiler' (F:\AI\ComfyUI-Nightly\ComfyUI\venv\lib\site-packages\triton\compiler\compiler.py)

Set TORCHDYNAMO_VERBOSE=1 for the internal stack trace (please do this especially if you're reporting a bug to PyTorch). For even more developer context, set TORCH_LOGS="+dynamo"

Traceback (most recent call last):
  File "F:\AI\ComfyUI-Nightly\ComfyUI\execution.py", line 496, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
  File "F:\AI\ComfyUI-Nightly\ComfyUI\execution.py", line 315, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
  File "F:\AI\ComfyUI-Nightly\ComfyUI\execution.py", line 289, in _async_map_node_over_list
    await process_inputs(input_dict, i)
  File "F:\AI\ComfyUI-Nightly\ComfyUI\execution.py", line 277, in process_inputs
    result = f(**inputs)
  File "F:\AI\ComfyUI-Nightly\ComfyUI\nodes.py", line 1525, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
  File "F:\AI\ComfyUI-Nightly\ComfyUI\nodes.py", line 1492, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "F:\AI\ComfyUI-Nightly\ComfyUI\comfy\sample.py", line 45, in sample
    samples = sampler.sample(noise, positive, negative, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "F:\AI\ComfyUI-Nightly\ComfyUI\comfy\samplers.py", line 1161, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "F:\AI\ComfyUI-Nightly\ComfyUI\comfy\samplers.py", line 1051, in sample
    return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "F:\AI\ComfyUI-Nightly\ComfyUI\comfy\samplers.py", line 1036, in sample
    output = executor.execute(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "F:\AI\ComfyUI-Nightly\ComfyUI\comfy\patcher_extension.py", line 112, in execute
    return self.original(*args, **kwargs)
  File "F:\AI\ComfyUI-Nightly\ComfyUI\comfy\samplers.py", line 1004, in outer_sample
    output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "F:\AI\ComfyUI-Nightly\ComfyUI\comfy\samplers.py", line 987, in inner_sample
    samples = executor.execute(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
  File "F:\AI\ComfyUI-Nightly\ComfyUI\comfy\patcher_extension.py", line 112, in execute
    return self.original(*args, **kwargs)
  File "F:\AI\ComfyUI-Nightly\ComfyUI\comfy\samplers.py", line 759, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
  File "F:\AI\ComfyUI-Nightly\ComfyUI\custom_nodes\RES4LYF\beta\__init__.py", line 167, in sample_res_2s
    return rk_sampler_beta.sample_rk_beta(model, x, sigmas, None, extra_args, callback, disable, rk_type="res_2s",)
  File "F:\AI\ComfyUI-Nightly\ComfyUI\venv\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "F:\AI\ComfyUI-Nightly\ComfyUI\custom_nodes\RES4LYF\beta\rk_sampler_beta.py", line 1665, in sample_rk_beta
    eps_[row], data_[row] = RK(x_tmp, s_tmp, x_0, sigma, transformer_options={'row': row, 'x_tmp': x_tmp, 'sigma_next': sigma_next})
  File "F:\AI\ComfyUI-Nightly\ComfyUI\custom_nodes\RES4LYF\beta\rk_method_beta.py", line 901, in __call__
    denoised = self.model_denoised(x.to(self.model_device), sub_sigma.to(self.model_device), **self.extra_args).to(sigma.device)
  File "F:\AI\ComfyUI-Nightly\ComfyUI\custom_nodes\RES4LYF\beta\rk_method_beta.py", line 241, in model_denoised
    denoised = self.model(x, sigma * s_in, **extra_args)
  File "F:\AI\ComfyUI-Nightly\ComfyUI\comfy\samplers.py", line 408, in __call__
    out = self.inner_model(x, sigma, model_options=model_options, seed=seed)
  File "F:\AI\ComfyUI-Nightly\ComfyUI\comfy\samplers.py", line 960, in __call__
    return self.outer_predict_noise(*args, **kwargs)
  File "F:\AI\ComfyUI-Nightly\ComfyUI\comfy\samplers.py", line 967, in outer_predict_noise
    ).execute(x, timestep, model_options, seed)
  File "F:\AI\ComfyUI-Nightly\ComfyUI\comfy\patcher_extension.py", line 112, in execute
    return self.original(*args, **kwargs)
  File "F:\AI\ComfyUI-Nightly\ComfyUI\comfy\samplers.py", line 970, in predict_noise
    return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed)
  File "F:\AI\ComfyUI-Nightly\ComfyUI\comfy\samplers.py", line 388, in sampling_function
    out = calc_cond_batch(model, conds, x, timestep, model_options)
  File "F:\AI\ComfyUI-Nightly\ComfyUI\comfy\samplers.py", line 206, in calc_cond_batch
    return _calc_cond_batch_outer(model, conds, x_in, timestep, model_options)
  File "F:\AI\ComfyUI-Nightly\ComfyUI\comfy\samplers.py", line 214, in _calc_cond_batch_outer
    return executor.execute(model, conds, x_in, timestep, model_options)
  File "F:\AI\ComfyUI-Nightly\ComfyUI\comfy\patcher_extension.py", line 112, in execute
    return self.original(*args, **kwargs)
  File "F:\AI\ComfyUI-Nightly\ComfyUI\comfy\samplers.py", line 333, in _calc_cond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
  File "F:\AI\ComfyUI-Nightly\ComfyUI\comfy\model_base.py", line 161, in apply_model
    return comfy.patcher_extension.WrapperExecutor.new_class_executor(
  File "F:\AI\ComfyUI-Nightly\ComfyUI\comfy\patcher_extension.py", line 113, in execute
    return self.wrappers[self.idx](self, *args, **kwargs)
  File "F:\AI\ComfyUI-Nightly\ComfyUI\comfy_api\torch_helpers\torch_compile.py", line 26, in apply_torch_compile_wrapper
    return executor(*args, **kwargs)
  File "F:\AI\ComfyUI-Nightly\ComfyUI\comfy\patcher_extension.py", line 105, in __call__
    return new_executor.execute(*args, **kwargs)
  File "F:\AI\ComfyUI-Nightly\ComfyUI\comfy\patcher_extension.py", line 112, in execute
    return self.original(*args, **kwargs)
  File "F:\AI\ComfyUI-Nightly\ComfyUI\comfy\model_base.py", line 200, in _apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
  File "F:\AI\ComfyUI-Nightly\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1767, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "F:\AI\ComfyUI-Nightly\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1778, in _call_impl
    return forward_call(*args, **kwargs)
  File "F:\AI\ComfyUI-Nightly\ComfyUI\comfy\ldm\wan\model.py", line 614, in forward
    return comfy.patcher_extension.WrapperExecutor.new_class_executor(
  File "F:\AI\ComfyUI-Nightly\ComfyUI\comfy\patcher_extension.py", line 112, in execute
    return self.original(*args, **kwargs)
  File "F:\AI\ComfyUI-Nightly\ComfyUI\comfy\ldm\wan\model.py", line 634, in _forward
    return self.forward_orig(x, timestep, context, clip_fea=clip_fea, freqs=freqs, transformer_options=transformer_options, **kwargs)[:, :, :t, :h, :w]
  File "F:\AI\ComfyUI-Nightly\ComfyUI\comfy\ldm\wan\model.py", line 579, in forward_orig
    x = block(x, e=e0, freqs=freqs, context=context, context_img_len=context_img_len, transformer_options=transformer_options)
  File "F:\AI\ComfyUI-Nightly\ComfyUI\venv\lib\site-packages\torch\_dynamo\eval_frame.py", line 372, in __call__
    return super().__call__(*args, **kwargs)
  File "F:\AI\ComfyUI-Nightly\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1767, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "F:\AI\ComfyUI-Nightly\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1778, in _call_impl
    return forward_call(*args, **kwargs)
  File "F:\AI\ComfyUI-Nightly\ComfyUI\venv\lib\site-packages\torch\_dynamo\eval_frame.py", line 712, in _fn
    raise e.remove_dynamo_frames() from None  # see TORCHDYNAMO_VERBOSE=1
  File "F:\AI\ComfyUI-Nightly\ComfyUI\venv\lib\site-packages\torch\_dynamo\output_graph.py", line 1636, in _call_user_compiler
    raise BackendCompilerFailed(
  File "F:\AI\ComfyUI-Nightly\ComfyUI\venv\lib\site-packages\torch\_dynamo\output_graph.py", line 1611, in _call_user_compiler
    compiled_fn = compiler_fn(gm, self.example_inputs())
  File "F:\AI\ComfyUI-Nightly\ComfyUI\venv\lib\site-packages\torch\_dynamo\repro\after_dynamo.py", line 150, in __call__
    compiled_gm = compiler_fn(gm, example_inputs)
  File "F:\AI\ComfyUI-Nightly\ComfyUI\venv\lib\site-packages\torch\__init__.py", line 2364, in __call__
    return compile_fx(model_, inputs_, config_patches=self.config)
  File "F:\AI\ComfyUI-Nightly\ComfyUI\venv\lib\site-packages\torch\_inductor\compile_fx.py", line 2358, in compile_fx
    return aot_autograd(
  File "F:\AI\ComfyUI-Nightly\ComfyUI\venv\lib\site-packages\torch\_dynamo\backends\common.py", line 106, in __call__
    cg = aot_module_simplified(gm, example_inputs, **self.kwargs)
  File "F:\AI\ComfyUI-Nightly\ComfyUI\venv\lib\site-packages\torch\_functorch\aot_autograd.py", line 1189, in aot_module_simplified
    compiled_fn = AOTAutogradCache.load(
  File "F:\AI\ComfyUI-Nightly\ComfyUI\venv\lib\site-packages\torch\_functorch\_aot_autograd\autograd_cache.py", line 923, in load
    compiled_fn = dispatch_and_compile()
  File "F:\AI\ComfyUI-Nightly\ComfyUI\venv\lib\site-packages\torch\_functorch\aot_autograd.py", line 1174, in dispatch_and_compile
    compiled_fn, _ = create_aot_dispatcher_function(
  File "F:\AI\ComfyUI-Nightly\ComfyUI\venv\lib\site-packages\torch\_functorch\aot_autograd.py", line 576, in create_aot_dispatcher_function
    return _create_aot_dispatcher_function(
  File "F:\AI\ComfyUI-Nightly\ComfyUI\venv\lib\site-packages\torch\_functorch\aot_autograd.py", line 836, in _create_aot_dispatcher_function
    compiled_fn, fw_metadata = compiler_fn(
  File "F:\AI\ComfyUI-Nightly\ComfyUI\venv\lib\site-packages\torch\_functorch\_aot_autograd\jit_compile_runtime_wrappers.py", line 243, in aot_dispatch_base
    compiled_fw = compiler(fw_module, updated_flat_args)
  File "F:\AI\ComfyUI-Nightly\ComfyUI\venv\lib\site-packages\torch\_functorch\aot_autograd.py", line 483, in __call__
    return self.compiler_fn(gm, example_inputs)
  File "F:\AI\ComfyUI-Nightly\ComfyUI\venv\lib\site-packages\torch\_inductor\compile_fx.py", line 2190, in fw_compiler_base
    return inner_compile(
  File "F:\AI\ComfyUI-Nightly\ComfyUI\venv\lib\site-packages\torch\_inductor\compile_fx.py", line 716, in compile_fx_inner
    return wrap_compiler_debug(_compile_fx_inner, compiler_name="inductor")(
  File "F:\AI\ComfyUI-Nightly\ComfyUI\venv\lib\site-packages\torch\_dynamo\repro\after_aot.py", line 124, in debug_wrapper
    inner_compiled_fn = compiler_fn(gm, example_inputs)
  File "F:\AI\ComfyUI-Nightly\ComfyUI\venv\lib\site-packages\torch\_inductor\compile_fx.py", line 823, in _compile_fx_inner
    (key_info, cache_info) = FxGraphCache.prepare_key(
  File "F:\AI\ComfyUI-Nightly\ComfyUI\venv\lib\site-packages\torch\_inductor\codecache.py", line 1399, in prepare_key
    key, debug_lines = compiled_fx_graph_hash(
  File "F:\AI\ComfyUI-Nightly\ComfyUI\venv\lib\site-packages\torch\_inductor\codecache.py", line 905, in compiled_fx_graph_hash
    details = FxGraphHashDetails(gm, example_inputs, fx_kwargs, inputs_to_check)
  File "F:\AI\ComfyUI-Nightly\ComfyUI\venv\lib\site-packages\torch\_inductor\codecache.py", line 877, in __init__
    self.system_info = CacheBase.get_system()
  File "F:\AI\ComfyUI-Nightly\ComfyUI\venv\lib\site-packages\torch\_inductor\codecache.py", line 188, in get_system
    from triton.compiler.compiler import triton_key
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
ImportError: cannot import name 'triton_key' from 'triton.compiler.compiler' (F:\AI\ComfyUI-Nightly\ComfyUI\venv\lib\site-packages\triton\compiler\compiler.py)

Set TORCHDYNAMO_VERBOSE=1 for the internal stack trace (please do this especially if you're reporting a bug to PyTorch). For even more developer context, set TORCH_LOGS="+dynamo"

```

```
backend='inductor' raised:
ImportError: cannot import name 'triton_key' from 'triton.compiler.compiler' (F:\AI\ComfyUI-Nightly\ComfyUI\venv\lib\site-packages\triton\compiler\compiler.py)

Set TORCHDYNAMO_VERBOSE=1 for the internal stack trace (please do this especially if you're reporting a bug to PyTorch). For even more developer context, set TORCH_LOGS="+dynamo"
```

I have latest nightly comfy + torch 2.8.0.dev20250521+cu128 installed. It was working fine with 3.3.1.post19.

Do I need to upgrade torch to 2.9?

**Comment by woct0rdho** [comment]
@jprsyt5 Triton 3.5 may not work with an earlier nightly version of torch 2.8 . I only tested that it works with the stable version of torch 2.8, and the release candidate version (downloaded from the 'test' channel, should be almost identical to the last nightly version and the stable version) of torch 2.9 .

**Comment by jtabox** [comment]
> @woct0rdho yesterday i have generated FP8 Scaled version of Qwen Image Edit 2509 model and it is like 1.5x faster inference compared to GGUF and same quality
> 
> i don't see any benefit of GGUF anymore unless you are going for lower ranks like Q5 perhaps
> 
> i am using with native comfyui

What script are you using for the conversion to scaled? This one? https://github.com/Clybius/Learned-Rounding

**Comment by FurkanGozukara** [comment]
> > @woct0rdho yesterday i have generated FP8 Scaled version of Qwen Image Edit 2509 model and it is like 1.5x faster inference compared to GGUF and same quality
> > i don't see any benefit of GGUF anymore unless you are going for lower ranks like Q5 perhaps
> > i am using with native comfyui
> 
> What script are you using for the conversion to scaled? This one? https://github.com/Clybius/Learned-Rounding

I coded myself based on Musubi Tuner https://github.com/kohya-ss/musubi-tuner

Kohya is a legend. he also recently analyzed and visually compared different scaling methods and upgraded his fp8 scaling method

**Comment by pivtienduc** [comment]
> @jprsyt5 Triton 3.5 may not work with an earlier nightly version of torch 2.8 . I only tested that it works with the stable version of torch 2.8, and the release candidate version (downloaded from the 'test' channel, should be almost identical to the last nightly version and the stable version) of torch 2.9 .

Hi @woct0rdho 

I can confirm the compile haven't worked yet, speed haven't changed either compile or not. This is my working workflow for Qwen fp8. This is also the only working workflow, otherwise ComfyUI create black image.

image

Not working workflow:

image

This is comfyUI settings, I use Pytorch 2.9 stable version, cuda 12.8 and GPU 3090, I already installed triton triton-windows 3.5.0.post2.1

image

**Comment by woct0rdho** [comment]
@jprsyt5 What's your MSVC version (you can see it when modifying the components in your Visual Studio)? What if you update it to the latest version?

**Comment by jprsyt5** [comment]
> @jprsyt5 What's your MSVC version (you can see it when modifying the components in your Visual Studio)? What if you update it to the latest version?

C:\Users\user>"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat"
**********************************************************************
** Visual Studio 2022 Developer Command Prompt v17.7.4
** Copyright (c) 2022 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'

C:\Users\user>cl
Microsoft (R) C/C++ Optimizing Compiler Version 19.37.32824 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

usage: cl [ option... ] filename... [ /link linkoption... ]

image

Tried checking in Visual Studio Installer, and it shows as the latest version
