### ISSUE TITLE
AttrDescriptor error while calling generate method on a model

### ISSUE THREAD

**Issue by tatyanavidrevich** [woct0rdho/triton-windows#97]
I am getting the following error while calling generate method with paligemma2:
ImportError: cannot import name 'AttrsDescriptor' from 'triton.compiler.compiler' (...\site-packages\triton\compiler\compiler.py)

here is more complete stack trace:
    generation = base_model.generate(**model_inputs, max_new_tokens=max_new_tokens)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\venv\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "...\venv\Lib\site-packages\transformers\generation\utils.py", line 2223, in generate
    result = self._sample(
             ^^^^^^^^^^^^^
  File "...\venv\Lib\site-packages\transformers\generation\utils.py", line 3197, in _sample
    model_forward = self.get_compiled_call(generation_config.compile_config)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\venv\Lib\site-packages\transformers\modeling_utils.py", line 5265, in get_compiled_call
    self._compiled_call = torch.compile(self.__call__, **compile_config.to_dict())
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\venv\Lib\site-packages\torch\__init__.py", line 2565, in compile
    return torch._dynamo.optimize(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "...\venv\Lib\site-packages\torch\_dynamo\eval_frame.py", line 842, in optimize
    return _optimize(rebuild_ctx, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\venv\Lib\site-packages\torch\_dynamo\eval_frame.py", line 896, in _optimize
    backend = get_compiler_fn(backend)
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\venv\Lib\site-packages\torch\_dynamo\eval_frame.py", line 783, in get_compiler_fn
    from .repro.after_dynamo import wrap_backend_debug
  File "...\venv\Lib\site-packages\torch\_dynamo\repro\after_dynamo.py", line 16, in <module>
    from torch._dynamo.debug_utils import (
  File "...\venv\Lib\site-packages\torch\_dynamo\debug_utils.py", line 25, in <module>
    from torch._dynamo.testing import rand_strided
  File "...\venv\Lib\site-packages\torch\_dynamo\testing.py", line 27, in <module>
    from torch._dynamo.backends.debugging import aot_eager
  File "...\venv\Lib\site-packages\torch\_dynamo\backends\debugging.py", line 10, in <module>
    from functorch.compile import min_cut_rematerialization_partition
  File "...\venv\Lib\site-packages\functorch\compile\__init__.py", line 2, in <module>
    from torch._functorch.aot_autograd import (
  File "...\venv\Lib\site-packages\torch\_functorch\aot_autograd.py", line 36, in <module>
    from torch._inductor.output_code import OutputCode
  File "...\venv\Lib\site-packages\torch\_inductor\output_code.py", line 47, in <module>
    from torch._inductor.cudagraph_utils import (
  File "...\venv\Lib\site-packages\torch\_inductor\cudagraph_utils.py", line 10, in <module>
    from torch._inductor.utils import InputType
  File "...\venv\Lib\site-packages\torch\_inductor\utils.py", line 50, in <module>
    from torch._inductor.runtime.hints import DeviceProperties
  File "...\venv\Lib\site-packages\torch\_inductor\runtime\hints.py", line 67, in <module>
    from triton.compiler.compiler import AttrsDescriptor
ImportError: cannot import name 'AttrsDescriptor' from 'triton.compiler.compiler' (...\venv\Lib\site-packages\triton\compiler\compiler.py)

Would you please recommend what I can do?

**Comment by woct0rdho** [comment]
What are your PyTorch version and Triton version?

Triton 3.2 only works with PyTorch >= 2.6, and Triton 3.3 (pre-release) only works with PyTorch >= 2.7 (nightly).

See https://github.com/woct0rdho/triton-windows#3-pytorch

**Comment by tatyanavidrevich** [comment]
Thank you, that explains it - I downgraded Triton since I use pytorch 2.6 and I works!
